config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'rails_admin/main#dashboard'

  resources :workers do
    collection do
      get 'search'
    end
    resources :computers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/char.rb
class Char < ApplicationRecord
  belongs_to :datashow, :inverse_of => :char
end

app/models/charprinter.rb
class Charprinter < ApplicationRecord
  belongs_to :printer, :inverse_of => :charprinters
end

app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :worker

  mount_uploader :bill, BillUploader

  has_many :tasks, :dependent => :destroy, :inverse_of => :computer
  accepts_nested_attributes_for :tasks, :allow_destroy => true

  has_many :documents, :dependent => :destroy, :inverse_of => :computer
  accepts_nested_attributes_for :documents, :allow_destroy => true

  has_many :softwares, :dependent => :destroy, :inverse_of => :computer
  accepts_nested_attributes_for :softwares, :allow_destroy => true
end

app/models/datashow.rb
class Datashow < ApplicationRecord
  has_many :chars, :dependent => :destroy, :inverse_of => :datashow
  accepts_nested_attributes_for :chars, :allow_destroy => true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :computer, :inverse_of => :documents
end

app/models/harddrive.rb
class Harddrive < ApplicationRecord
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :worker

  mount_uploader :bill, BillUploader
  mount_uploader :delivery_file, BillUploader
end

app/models/printer.rb
class Printer < ApplicationRecord
  belongs_to :worker
  has_many :charprinters, :dependent => :destroy, :inverse_of => :printer
  accepts_nested_attributes_for :charprinters, :allow_destroy => true
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :worker
end

app/models/server.rb
class Server < ApplicationRecord
  has_many :virtuals, :dependent => :destroy, :inverse_of => :server
  accepts_nested_attributes_for :virtuals, :allow_destroy => true
end

app/models/software.rb
class Software < ApplicationRecord
  belongs_to :computer, :inverse_of => :softwares
end

app/models/switch.rb
class Switch < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :computer, :inverse_of => :tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :authentication_keys => [:username]
end

app/models/virtual.rb
class Virtual < ApplicationRecord
  belongs_to :server, :inverse_of => :virtuals
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
end

app/models/worker.rb
class Worker < ApplicationRecord
  searchkick
  
  has_one :computer
  has_one :screen
  has_one :printer
  has_one :notebook
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show]

  def search
    if params[:search].present?
      @workers = Worker.search(params[:search])
    else
      @workers = Worker.all
    end
  end

  def index
    @workers = Worker.all
  end

  def show
  end

  private

  def set_worker
    @worker = Worker.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/index.html.slim
h1 Funcionarios

p Listado de funcionarios con equipos informaticos asignados.
hr
.panel.panel-primary
  .panel-heading Computadores
  .panel-body
    table.table
      thead
        tr
          th Nombre funcionario
          th Opciones
        tbody
          - @workers.each do |worker|
            tr
              td= worker.name
              td= link_to 'Ver funcionario', worker, class: 'btn btn-primary'

app/views/workers/search.html.slim
h1 Funcionarios

p Listado de funcionarios con equipos informaticos asignados.
hr

= form_tag search_workers_path, method: :get, role: "search" do
  p= text_field_tag :search, params[:search], class: 'form-control'
  p= submit_tag "Buscar", name: nil, class: 'btn btn-default'

.panel.panel-primary
  .panel-heading Computadores
  .panel-body
    table.table
      thead
        tr
          th Nombre funcionario
          th Opciones
        tbody
          - @workers.each do |worker|
            tr
              td= worker.name
              td= link_to 'Ver funcionario', worker, class: 'btn btn-primary'

app/views/workers/show.html.slim
h1 Asignacion de equipo a
h3= @worker.name
hr
.row
  .col-md-6
    .panel.panel-primary
      .panel-heading EQUIPO COMPUTACIONAL
      .panel-body
        - if @worker.computer.blank?
          p Sin equipo asignado
        - else
          strong
            p Marca:
          p= @worker.computer.name unless @worker.computer.blank?
          strong
            p Modelo:
          p= @worker.computer.model unless @worker.computer.blank?
          strong
            p Numero de serie:
          p= @worker.computer.serial unless @worker.computer.blank?
  .col-md-6
    .panel.panel-primary
      .panel-heading NOTEBOOK
      .panel-body
        - if @worker.notebook.blank?
          p Sin notebook asignado
        - else
          p Marca:
          p= @worker.notebook.name unless @worker.notebook.blank?
          p Modelo:
          p= @worker.notebook.model unless @worker.notebook.blank?
          p Numero de serie:
          p= @worker.notebook.serial unless @worker.notebook.blank?

.panel.panel-primary
  .panel-heading IMPRESORAS
  .panel-body
    - if @worker.printer.blank?
      p Sin impresora asignada
    - else
      p Marca:
      p= @worker.printer.name unless @worker.printer.blank?
      p Modelo:
      p= @worker.printer.model unless @worker.printer.blank?
      p Numero de serie:
      p= @worker.printer.serial unless @worker.printer.blank?

= link_to 'Volver', workers_path, class: 'btn btn-primary'